export module ddge.modules.vulkan.extension_inspection;

export import ddge.modules.vulkan.extension_inspection.extension_is_promoted_to_vulkan1x;
export import ddge.modules.vulkan.extension_inspection.extensions_promoted_to_vulkan1x;
export import ddge.modules.vulkan.extension_inspection.try_promote_extension_to_vulkan1x;
