= Building

== Toolchain

The project is required to work with *Clang 22* and *Microsoft's STL*.

Support for other setups is not a priority until a planned release.

.How to get Clang on Windows?
[%collapsible]
====
Use the https://github.com/llvm/llvm-project/releases[official installer].
====

== CMake

External libraries used to be fetched with CMake's https://cmake.org/cmake/help/latest/module/FetchContent.html[FetchContent].
This got too slow as the project grew, hence the move to a package manager.

FetchContent is still used for libraries that don't have the proper versions in a remote.

== Conan

https://docs.conan.io/2/[Conan 2] is used as the project's primary dependency manager.

You can install Conan using pip https://docs.conan.io/2/installation.html[tutorial].
After this, you would probably want to set up a
_Conan https://docs.conan.io/2/reference/config_files/profiles.html=profiles[profile]_ to use with this project.

Run `+conan install . -b=missing+` to set up all the third-party dependencies (or `+conan install . -b=missing --profile:host=customprofile --profile:build=customprofile+` to make sure it uses the right profile).
This will create a _CMakeUserPresets.json_ file inside the working directory that can be used to build the project (with your IDE).

.Conan profile example
[%collapsible%open]
====
----
[settings]
os=Windows
arch=x86_64
build_type=Debug
compiler=clang
compiler.cppstd=26
compiler.version=22
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.runtime_version=v145

[conf]
tools.build:compiler_executables={'c':'C:/Program Files/LLVM/bin/clang.exe','cpp':'C:/Program Files/LLVM/bin/clang++.exe'}
tools.cmake.cmaketoolchain:generator=Ninja
user.data-driven_game_engine:dev=True
user.data-driven_game_engine:debug=True
user.data-driven_game_engine:enable_tests=True
user.data-driven_game_engine:enable_examples=True

[buildenv]
PATH+=(path)C:/Program Files/LLVM/bin
PATH+=(path)C:/Program Files/CMake/bin
PATH+=(path)C:/Program Files/Ninja

[platform_tool_requires]
cmake/4.3
----
====

.How to test the library as a package?
[%collapsible]
====
Run the following command: `+conan export-pkg .+` +
Read more https://docs.conan.io/2/tutorial/developing_packages/local_package_development_flow.html#conan-export-pkg[here].
====

== Vulkan

Generally, Vulkan development is heavy to setup without the https://www.lunarg.com/vulkan-sdk/[Vulkan SDK].
Useful tools included in the SDK are the *_glslc_* shader compiler and the *Vulkan Validation Layers*.

glslc may be installed separately.
The Vulkan Validation Layers are optional.
